apiVersion: v1
type: kubernetes.io/dockerconfigjson
metadata:
  name: london-pull-secret
  namespace: {{ .Release.Namespace }}
data:
    .dockerconfigjson: {{ template "secretTemplate" . }}
kind: Secret
